## 一种使用类别分布的离散策略

In [1]:
from torch.distributions import Categorical
import torch

# 在策略网络中得到概率
policy_net_output = torch.tensor([-1.6094, -0.2231])



In [2]:
policy_net_output

tensor([-1.6094, -0.2231])

In [3]:
pdparams = policy_net_output

In [4]:
pdparams

tensor([-1.6094, -0.2231])

In [5]:
pd = Categorical(logits=pdparams)
pd

Categorical(logits: torch.Size([2]))

In [6]:
pd.probs

tensor([0.2000, 0.8000])

In [7]:
action = pd.sample()
action

tensor(1)

tensor(1) 也就是向右移动

In [8]:
pd.log_prob(action)

tensor(-0.2231)

## 对于连续策略的构造

In [9]:
from torch.distributions import Normal
import torch

policy_net_output = torch.tensor([1.0, 0.2])
#                                 mean, std
pdparams = policy_net_output
pd = Normal(loc=pdparams[0], scale=pdparams[1])

In [10]:
pd

Normal(loc: 1.0, scale: 0.20000000298023224)

In [12]:
action = pd.sample()
action

tensor(1.0584)

In [13]:
pd.log_prob(action)

tensor(0.6478)